spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - role.read
        provider:
          spring:
            issuer-uri: http://localhost:8081
  cloud:
    gateway:
      routes:
        - id: dummy
          uri: lb://DUMMY-SERVICE
          predicates:
            - Path=/
          filters:
            - TokenRelay=
        - id: register
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/auth/register
          filters:
            - TokenRelay=

logging:
  level:
    org.springframework:
      security: trace
      cloud: trace