spring.application.name: gateway
server.port: 8080

#spring:
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        serviceId: config-server
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

spring:
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
        provider:
          spring:
            issuer-uri: http://localhost:8081
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins:
              - "http://localhost:8081"
              - "http://localhost:8080"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
      routes:
        - id: register
          uri: "http://localhost:8081"
          predicates:
            - Path=/api/auth/register
          filters:
            - TokenRelay=
        - id: login
          uri: "http://localhost:8081"
          predicates:
            - Path=/api/auth/login
          filters:
            - TokenRelay=
        - id: dummy
          uri: "http://localhost:8082"
          predicates:
            - Path=/api/token
          filters:
            - TokenRelay=
        - id: react_app
          uri: "http://localhost:5173"
          predicates:
            - Path=/**
          filters:
            - TokenRelay=

logging:
  level:
    org.springframework:
      security: trace
      cloud: trace