spring.application.name: config-server
server.port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/IdeaProjects/SpringCloudDemo/config

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true